# Nombre del workflow
name: Build de Angular app

# Disparadores de este workflow/pipeline
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Inicia la cadena de montaje
jobs:
  build:
    # Sistema operativo sobre el que se va a ejecutar el workflow/pipeline
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [12.x]

    # Pasos/fases de nuestra cadena de montaje
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Instalar Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.8
      
      - name: Instalar dependencias/modulos
        run: npm install
      
      - name: Build/Ejecutar
        run: npm run build -- --prod

      - name: Ejecutar tests
        run: npm run test-headless
